-- ============================================================================
--  Estoque de T.I. — Schema Supabase (banco compartilhado multi-dispositivo)
--  Executar no SQL Editor do Supabase (uma vez).
-- ============================================================================

-- ---- Lojas ----
create table if not exists public.lojas (
  id bigint generated by default as identity primary key,
  nome text not null,
  codigo text not null default '',
  endereco text,
  contato text,
  ativo boolean not null default true
);

-- ---- Categorias ----
create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  ativa boolean not null default true
);

-- ---- Fornecedores ----
create table if not exists public.fornecedores (
  id bigint generated by default as identity primary key,
  nome text not null,
  cnpj text,
  contato text,
  telefone text,
  email text,
  ativo boolean not null default true
);

-- ---- Produtos ----
create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  codigo text not null default '',
  nome text not null,
  marca text,
  modelo text,
  descricao text,
  categoria_id bigint,
  categoria_nome text,
  fornecedor_id bigint,
  fornecedor_nome text,
  unidade text not null default 'UN',
  preco_compra double precision not null default 0,
  preco_venda double precision not null default 0,
  estoque double precision not null default 0,
  estoque_minimo double precision not null default 0,
  ativo boolean not null default true
);

-- ---- Usuarios ----
create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null unique,
  senha text,
  perfil text not null default 'operador',
  loja_id bigint,
  loja_nome text,
  ativo boolean not null default true
);

-- ---- Movimentacoes ----
create table if not exists public.movimentacoes (
  id bigint generated by default as identity primary key,
  tipo text not null,
  produto_id bigint not null,
  produto_nome text,
  produto_codigo text,
  quantidade double precision not null default 0,
  loja_origem_id bigint,
  loja_origem_nome text,
  loja_destino_id bigint,
  loja_destino_nome text,
  usuario_id bigint,
  observacao text,
  data_movimento timestamptz not null default now(),
  preco_compra double precision,
  unidade double precision
);

-- ---- Solicitacoes ----
create table if not exists public.solicitacoes (
  id bigint generated by default as identity primary key,
  loja_id bigint not null,
  loja_nome text,
  usuario_id bigint,
  usuario_nome text,
  observacao text,
  status text not null default 'pendente',
  data_solicitacao timestamptz not null default now(),
  total_itens integer
);

create table if not exists public.solicitacao_itens (
  id bigint generated by default as identity primary key,
  solicitacao_id bigint not null references public.solicitacoes(id) on delete cascade,
  produto_id bigint not null,
  produto_nome text,
  produto_codigo text,
  unidade text,
  quantidade double precision not null default 0
);

-- ---- Pedidos ----
create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  numero text not null,
  loja_id bigint,
  loja_nome text,
  loja_codigo text,
  solicitante text not null default '',
  setor text,
  origem text,
  status text not null default 'importado',
  arquivo_pdf text,
  data_pedido timestamptz not null default now()
);

create table if not exists public.pedido_itens (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  produto_id bigint,
  produto_nome text,
  unidade text,
  quantidade double precision not null default 0
);

-- ---- Alertas ----
create table if not exists public.alertas (
  id bigint generated by default as identity primary key,
  tipo text not null default 'estoque',
  titulo text not null,
  mensagem text not null default '',
  data_alerta timestamptz not null default now(),
  lido boolean not null default false
);

-- ============================================================================
--  RLS — acesso anonimo total nas tabelas de DADOS OPERACIONAIS
--  (ferramenta interna; autenticacao e feita na camada da aplicacao).
--  Sem isso o REST bloqueia tudo por padrao.
--
--  A tabela public.usuarios NAO recebe policy permissiva de tabela inteira:
--  ela contem a coluna `senha` (hash argon2) e nao deve ser lida/gravada
--  integralmente pela anon key. Veja a secao "Hardening usuarios" abaixo.
-- ============================================================================
alter table public.lojas enable row level security;
alter table public.categorias enable row level security;
alter table public.fornecedores enable row level security;
alter table public.produtos enable row level security;
alter table public.usuarios enable row level security;
alter table public.movimentacoes enable row level security;
alter table public.solicitacoes enable row level security;
alter table public.solicitacao_itens enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_itens enable row level security;
alter table public.alertas enable row level security;

do $$
declare t text;
begin
  foreach t in array array[
    'lojas','categorias','fornecedores','produtos','usuarios','movimentacoes',
    'solicitacoes','solicitacao_itens','pedidos','pedido_itens','alertas'
  ] loop
    execute format(
      'drop policy if exists "acesso_total_anon" on public.%I;', t);
    execute format(
      'create policy "acesso_total_anon" on public.%I for all to anon using (true) with check (true);', t);
  end loop;
end $$;

-- ============================================================================
--  Hardening da tabela usuarios
--  O app usa a anon key para TUDO (autenticacao na camada aplicacao), entao
--  nao podemos simplesmente fechar a tabela. Protegemos a coluna `senha`
--  com privilegios em nivel de COLUNA: anon le/atualiza apenas as colunas
--  de perfil, sem nunca SELECT/UPDATE do hash.
--  - INSERT mantem a coluna senha concedida, senao o app nao conseguiria
--    cadastrar usuario com senha inicial (risco residual baixo: quem insere
--    ja conhece o valor que esta inserindo).
--  - DELETE continua permitido por linha (remover uma linha nao expõe o
--    hash de outras).
--  Residual: qualquer pessoa com a anon key ainda pode criar linhas e ler
--  nome/email/perfil de todos os usuarios — aceitavel para ferramenta
--  interna; o caminho ideal no futuro é migrar para Supabase Auth.
-- ============================================================================
revoke all privileges on public.usuarios from anon;

grant select (id, nome, email, perfil, loja_id, loja_nome, ativo)
  on public.usuarios to anon;
grant insert (nome, email, senha, perfil, loja_id, loja_nome, ativo)
  on public.usuarios to anon;
grant update (nome, email, perfil, loja_id, loja_nome, ativo)
  on public.usuarios to anon;

-- Login: unica porta de entrada para o HASH da senha.
-- O hash retornado e argon2 — verifique com argon2-cffi no backend.
-- Futuro: substituir por Supabase Auth (OTP/magic link) e remover esta funcao.
create or replace function public.login_usuario(p_email text)
returns table (id bigint, nome text, email text, perfil text, senha_hash text, ativo boolean)
language sql stable security definer set search_path = public as $$
  select u.id, u.nome, u.email, u.perfil, u.senha, u.ativo
  from public.usuarios u
  where lower(u.email) = lower(p_email)
  limit 1;
$$;

grant execute on function public.login_usuario(text) to anon;

-- ============================================================================
--  Unique constraints (idempotentes via DO block; duplicatas nos dados
--  existentes geram apenas NOTICE, nao abortam o script).
-- ============================================================================
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'produtos_codigo_unico' and conrelid = 'public.produtos'::regclass
  ) then
    begin
      alter table public.produtos add constraint produtos_codigo_unico unique (codigo);
    exception when others then
      raise notice 'produtos_codigo_unico nao criada: %', sqlerrm;
    end;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'pedidos_numero_unico' and conrelid = 'public.pedidos'::regclass
  ) then
    begin
      alter table public.pedidos add constraint pedidos_numero_unico unique (numero);
    exception when others then
      raise notice 'pedidos_numero_unico nao criada: %', sqlerrm;
    end;
  end if;
end $$;

-- ============================================================================
--  Foreign keys faltantes (idempotentes, cada uma isolada: se houver dados
--  orfaos a constraint e pulada com NOTICE e o script segue rodando).
-- ============================================================================
do $$
begin
  -- produtos.categoria_id -> categorias(id): apagar categoria nao apaga produto
  if not exists (
    select 1 from pg_constraint where conname = 'fk_produtos_categoria'
      and conrelid = 'public.produtos'::regclass
  ) then
    begin
      alter table public.produtos
        add constraint fk_produtos_categoria
        foreign key (categoria_id) references public.categorias(id) on delete set null;
    exception when others then
      raise notice 'fk_produtos_categoria nao criada (dados orfaos?): %', sqlerrm;
    end;
  end if;

  -- produtos.fornecedor_id -> fornecedores(id)
  if not exists (
    select 1 from pg_constraint where conname = 'fk_produtos_fornecedor'
      and conrelid = 'public.produtos'::regclass
  ) then
    begin
      alter table public.produtos
        add constraint fk_produtos_fornecedor
        foreign key (fornecedor_id) references public.fornecedores(id) on delete set null;
    exception when others then
      raise notice 'fk_produtos_fornecedor nao criada (dados orfaos?): %', sqlerrm;
    end;
  end if;

  -- movimentacoes.produto_id -> produtos(id): historico nao pode ser órfão,
  -- mas apagar produto com histórico fica bloqueado (NO ACTION) — decisão segura.
  if not exists (
    select 1 from pg_constraint where conname = 'fk_movimentacoes_produto'
      and conrelid = 'public.movimentacoes'::regclass
  ) then
    begin
      alter table public.movimentacoes
        add constraint fk_movimentacoes_produto
        foreign key (produto_id) references public.produtos(id);
    exception when others then
      raise notice 'fk_movimentacoes_produto nao criada (dados orfaos?): %', sqlerrm;
    end;
  end if;

  -- solicitacoes.loja_id -> lojas(id): coluna NOT NULL, sem ON DELETE automatico
  if not exists (
    select 1 from pg_constraint where conname = 'fk_solicitacoes_loja'
      and conrelid = 'public.solicitacoes'::regclass
  ) then
    begin
      alter table public.solicitacoes
        add constraint fk_solicitacoes_loja
        foreign key (loja_id) references public.lojas(id);
    exception when others then
      raise notice 'fk_solicitacoes_loja nao criada (dados orfaos?): %', sqlerrm;
    end;
  end if;

  -- solicitacao_itens.produto_id -> produtos(id)
  if not exists (
    select 1 from pg_constraint where conname = 'fk_solicitacao_itens_produto'
      and conrelid = 'public.solicitacao_itens'::regclass
  ) then
    begin
      alter table public.solicitacao_itens
        add constraint fk_solicitacao_itens_produto
        foreign key (produto_id) references public.produtos(id);
    exception when others then
      raise notice 'fk_solicitacao_itens_produto nao criada (dados orfaos?): %', sqlerrm;
    end;
  end if;

  -- pedido_itens.produto_id -> produtos(id) (coluna nullable, SET NULL ao apagar produto)
  if not exists (
    select 1 from pg_constraint where conname = 'fk_pedido_itens_produto'
      and conrelid = 'public.pedido_itens'::regclass
  ) then
    begin
      alter table public.pedido_itens
        add constraint fk_pedido_itens_produto
        foreign key (produto_id) references public.produtos(id) on delete set null;
    exception when others then
      raise notice 'fk_pedido_itens_produto nao criada (dados orfaos?): %', sqlerrm;
    end;
  end if;
end $$;

-- ============================================================================
--  Esclarecimento sobre movimentacoes.unidade (double precision):
--  apesar do nome legado "unidade", a coluna armazena o PRECO UNITARIO da
--  movimentacao (numero). O codigo Rust/TS a le/escreve como number —
--  NAO renomear a coluna, isso quebraria o app.
-- ============================================================================
comment on column public.movimentacoes.unidade is
  'Preco unitario da movimentacao (double precision). Nome legado "unidade" mantido por compatibilidade com o app (Rust/TS); nao renomear.';

-- ============================================================================
--  Reparo de sequencias apos importar dados com IDs explicitos (seed).
--  Chamar via POST /rest/v1/rpc/repair_sequences
-- ============================================================================
create or replace function public.repair_sequences()
returns void language plpgsql security definer as $$
declare t text;
begin
  foreach t in array array[
    'lojas','categorias','fornecedores','produtos','usuarios','movimentacoes',
    'solicitacoes','solicitacao_itens','pedidos','pedido_itens','alertas'
  ] loop
    execute format(
      'select setval(pg_get_serial_sequence(''public.%I'', ''id''),
             coalesce((select max(id) from public.%I), 1));', t, t);
  end loop;
end $$;
